### ISSUE TITLE
custom dataset | metashape conversion

### ISSUE THREAD

**Issue by antoinebio** [yzslab/nerfstudio#17]
Hello,
I tried the NERFSTUDIO engine
from metashape source 
so I save xml from the gui.
here is a test with 1 single photo into psx 

![image](https://github.com/yzslab/nerfstudio/assets/30265851/8bf83bf8-1ef2-4ef8-89ad-e158d0083197)

but the script 

**** 

doesn't take into account the xml and parse all the source images folder

![image](https://github.com/yzslab/nerfstudio/assets/30265851/b3a0a83e-b17c-4277-b274-6e9f797ef1a0)

attached you will find the xml file used and exported from metashape. 
[cameras_pose_cam01_only_clean.zip](https://github.com/yzslab/nerfstudio/files/13347186/cameras_pose_cam01_only_clean.zip)

except a remaining camera model unused the structure looks ok though...

**Comment by yzslab** [comment]
The metashape conversion was not written by me. I recommend you submit such a issue to upstream: https://github.com/nerfstudio-project/nerfstudio.

I think the better way is to use the colmap SfM, rather than convert from metashpae's output.

**Comment by antoinebio** [comment]
different projets I tested worked well using agi2nerf.py as well.
That was also suggested if testing gaussian splatting.

so to my mind the issue is more with the NERFSTUDIO converter when I read xml and source image folders.

I will pull that issue to https://github.com/nerfstudio-project/nerfstudio.

COLMAP gives less versatility in 3D reconstruction than metashape.
 but  beginning users can start with COLMAP.

**Comment by antoinebio** [comment]
https://github.com/nerfstudio-project/nerfstudio/issues/2608
