### ISSUE TITLE
ns-render asks for config.xml

### ISSUE THREAD

**Issue by antoinebio** [yzslab/nerfstudio#18]
Hi

ns-render asks for config.xml

![image](https://github.com/yzslab/nerfstudio/assets/30265851/dad9d257-44cf-4e66-9ff5-93c0ad9f18ed)

where it is generated when one asks for a render into nerfstudio ?

![image](https://github.com/yzslab/nerfstudio/assets/30265851/7c11e958-a4f0-4e33-9e0c-d0cdb472a4b2)

any idea where it is located by default ?

![image](https://github.com/yzslab/nerfstudio/assets/30265851/ff859b72-6aab-441a-bc3e-78362c3adee0)

**Comment by yzslab** [comment]
The usage of the video renderer has already intruduced in README: https://github.com/yzslab/nerfstudio/tree/gaussian_splatting#usage

**Comment by antoinebio** [comment]
![image](https://github.com/yzslab/nerfstudio/assets/30265851/138f3838-81c8-4dbf-8d84-82d0537ca47a)
