### ISSUE TITLE
load and view Gaussian Splatting checkpoint (or intermediate iteration)

### ISSUE THREAD

**Issue by antoinebio** [yzslab/nerfstudio#19]
with command python .\nerfstudio\scripts\gaussian_splatting\run_viewer.py

is it possible to view  and displayan intermediate checkpoint ? while training ?
![image](https://github.com/yzslab/gaussian-splatting-lightning/assets/30265851/5e8abd20-1a7d-417b-878f-098066f22df8)

or should I do that with itermediate iteration ?
C:\gaussian-splatting\output\d8e93b3d-d\point_cloud\iteration_7000
![image](https://github.com/yzslab/nerfstudio/assets/30265851/1d0a2955-7fd1-438e-97f3-99dd3960c4be)

i guess option 2 ...?

**Comment by yzslab** [comment]
Option 2.
