### ISSUE TITLE
Gaussian Splatting - Viewport Freezes Immediately After Launch

### ISSUE THREAD

**Issue by jkl3848** [yzslab/nerfstudio#3]
**Describe the bug**
After loading my pre-trained gaussian splat into the scene, it will freeze almost immediately. I can continue to move around and I will see the grid move, but my scene is static. I've tried relaunching many times, and I will be able to move the scene for a couple seconds before it freezes again. Lowering the max res keeps it from freezing as quickly, but it still happens within about 10 seconds of launch. I dont think it is a hardware issue as I have used SIBR and InstantNGP without issue.

**To Reproduce**
1. Launch the viewer with a trained Gaussian Splat.
2. Navigate around the scene.

**Expected behavior**
I expect to be able to move around the scene freely. I expect some slowness on higher quality settings but even at the lowest nothing will move.

**Additional context**
Here is the console contents
```
RuntimeWarning: Windows does not yet support torch.compile and the performance will be affected.
  warnings.warn(
C:\Users\path\to\mini_conda\envs\nerfstudio\lib\site-packages\tyro\_fields.py:826: UserWarning: Mutable type <class 'nerfstudio.engine.trainer.TrainerConfig'> is used as a default value for `config`. This is dangerous! Consider using `dataclasses.field(default_factory=...)` or marking <class 'nerfstudio.engine.trainer.TrainerConfig'> as frozen.
  warnings.warn(
Loading trained model at iteration 7000


[15:40:08] disabled local writer                                                                           writer.py:186
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Users\path\to\mini_conda\envs\nerfstudio\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\path\to\NeRF\nerfstudio\nerfstudio\viewer\server\render_state_machine.py", line 173, in run
    outputs = self._render_img(action.cam_msg)
  File "C:\Users\path\to\NeRF\nerfstudio\nerfstudio\viewer\server\render_state_machine.py", line 154, in _render_img
    name=EventName.VIS_RAYS_PER_SEC, duration=num_rays / render_time, step=step, avg_over_steps=True
ZeroDivisionError: float division by zero
```

I have tried all of the suggestions under NOTES-

> Hold down the right button of your mouse to move the camera a little bit before pressing W, or your camera may be frozen after moving a short distance.
> A fixup has been submitted: https://github.com/nerfstudio-project/nerfstudio/pull/2404
> Or use this viewer: https://nsv.cslab.pro/23-09-08-1/?websocket_url=ws://localhost:7007
> Press F5 to refresh the page if the web viewer stops updating the content (not sure why currently, hard to reproduce). If you are creating camera path, click 'EXPORT PATH' to download your camera path before refreshing, and you can click 'LOAD PATH' to restore from the downloaded file later.

But none of these were able to fix the issue.

**Comment by yzslab** [comment]
Thanks for your detailed description. I will fix it soon.

**Comment by yzslab** [comment]
Hi, please switch to branch [zero_division_fix](https://github.com/yzslab/nerfstudio/tree/zero_division_fix) (`git fetch --all && git checkout zero_division_fix`), and tell me whether it works.
Thanks.

**Comment by jkl3848** [comment]
That fixed the issue. Thank you!
