### ISSUE TITLE
Relative/Absolute path for python module bug

### ISSUE THREAD

**Issue by shared-iconem** [yzslab/nerfstudio#7]
**Describe the bug**
I have the following error:
``` 
Traceback (most recent call last):
  File "scripts/gaussian_splatting/run_viewer.py", line 41, in <module>
    from nerfstudio.scripts.gaussian_splatting.gaussian_splatting_config import GaussianSplattingConfig
ModuleNotFoundError: No module named 'nerfstudio.scripts.gaussian_splatting' 
```

**To Reproduce**
Try to execute the command `python nerfstudio/scripts/gaussian_splatting/run_viewer.py --model-path GAUSSIAN_TRAINING_OUTPUT_MODEL_DIR
`

I have tried to put this particular module in relative 
(replaced `from nerfstudio.scripts.gaussian_splatting.gaussian_splatting_config import GaussianSplattingConfig`
to  `from gaussian_splatting_config import GaussianSplattingConfig`), but then all dependency error come from the gaussian_splatting_config.py that uses absolute path.

I haven't modified source file, all \_\_init__.py are still there.

**Comment by yzslab** [comment]
Hi, have you run `pip install -e .`?

**Comment by shared-iconem** [comment]
Hi, yes it installed successfully as well as plyfile, diff-gaussian-rasterization and simple-knn (even tho your environment doesn't use same torch/python versions as the official Gaussian Splatting).

**Comment by yzslab** [comment]
> Hi, yes it installed successfully as well as plyfile, diff-gaussian-rasterization and simple-knn (even tho your environment doesn't use same torch/python versions as the official Gaussian Splatting).

Are you using a virtual environment created for another nerfstudio?
Please try this and tell me whether it works: `PYTHONPATH=. python nerfstudio/scripts/gaussian_splatting/run_viewer.py ...`

**Comment by yzslab** [comment]
@shared-iconem 
I have redownload the code and recreated a virtual enviroment, but still unable to reproduce your error.
Please run `pip install -e .` on the <b>root directory of this repository</b> again (won't work on other nerfsutdio directory), or add `PYTHONPATH=.` before `python`.
