### ISSUE TITLE
How do I find the internal coordinate transformation between the input data and the output, like dataparser_transforms.json in NerfStudio

### ISSUE THREAD

**Issue by cyz2727327** [yzslab/nerfstudio#9]
Hey guys, 

I'm new to Gaussian Splatting but I've been playing with NerfStudio for a while. What I want to achieve is to align the .glb mesh model with the Gaussian NeRF rendering in the web viewer, which are both create from the same data captured with Polycam. 

I understand for training purposed you probably did some coordinate transformation, and I need this information in order to align the Gaussian NeRF rendering with the original mesh model. I can do this already in NerfStudio because they provide a _**dataparser_transforms.json**_ file in the output folder, which contains a transform matrix with the scale factor.

How do I get this in Gaussian Splatting? Thanks a lot in advance !

**Comment by yzslab** [comment]
Hi, the transformation is applied at render stage. 

It is calculated here: https://github.com/yzslab/nerfstudio/blob/dc86fc75a845e14a7363f7a33ba0b8bd833b4b49/nerfstudio/pipelines/gaussian_splatting_pipeline.py#L58-L66
and applied at here: https://github.com/yzslab/nerfstudio/blob/dc86fc75a845e14a7363f7a33ba0b8bd833b4b49/nerfstudio/models/gaussian_splatting.py#L113-L115

It will do `auto_reorient` by default. You can disable it by adding `--no-auto-reorient` parameter when you running `run_viewer.py` & `render.py`, then it will use the same coordinate system as your training data.

**Comment by cyz2727327** [comment]
> Hi, the transformation is applied at render stage.
> 
> It is calculated here:
> 
> https://github.com/yzslab/nerfstudio/blob/dc86fc75a845e14a7363f7a33ba0b8bd833b4b49/nerfstudio/pipelines/gaussian_splatting_pipeline.py#L58-L66
> 
> 
> and applied at here:
> https://github.com/yzslab/nerfstudio/blob/dc86fc75a845e14a7363f7a33ba0b8bd833b4b49/nerfstudio/models/gaussian_splatting.py#L113-L115
> 
> It will do `auto_reorient` by default. You can disable it by adding `--no-auto-reorient` parameter when you running `run_viewer.py` & `render.py`, then it will use the same coordinate system as your training data.

This is great info, thanks for your quick reply @yzslab. However, now that you mentioned this, I fear there is another coord transformation between the training input data and the trained gaussian model, and I also need to get that as well. The transform you mentioned is between the trained model and the web viewer. 

I guess that first transform is done during the Gaussian Splatting training, by any change you know anything about that as well? Thanks a ton in advance !

**Comment by yzslab** [comment]
> > Hi, the transformation is applied at render stage.
> > It is calculated here:
> > https://github.com/yzslab/nerfstudio/blob/dc86fc75a845e14a7363f7a33ba0b8bd833b4b49/nerfstudio/pipelines/gaussian_splatting_pipeline.py#L58-L66
> > 
> > and applied at here:
> > https://github.com/yzslab/nerfstudio/blob/dc86fc75a845e14a7363f7a33ba0b8bd833b4b49/nerfstudio/models/gaussian_splatting.py#L113-L115
> > 
> > It will do `auto_reorient` by default. You can disable it by adding `--no-auto-reorient` parameter when you running `run_viewer.py` & `render.py`, then it will use the same coordinate system as your training data.
> 
> This is great info, thanks for your quick reply @yzslab. However, now that you mentioned this, I fear there is another coord transformation between the training input data and the trained gaussian model, and I also need to get that as well. The transform you mentioned is between the trained model and the web viewer.
> 
> I guess that first transform is done during the Gaussian Splatting training, by any change you know anything about that as well? Thanks a ton in advance !

Hi, the gaussian splatting training doesn't do any transformation between the input and output.

**Comment by softyoda** [comment]
Hi, just for your information (as I struggled a lot before finding this issue), this default behavior should be more visible (in the readme or when you run the render). 

The `--no-auto-reorient` isn't recognized as an argument on my side, I had to modify default value of  `~nerfstudio/nerfstudio/scripts/gaussian_splatting/gaussian_splatting_config.py` line 38 to `    auto_reorient: bool = False`

I don't think this should be the default behavior, as for example it's possible to reuse an alignment from reality capture (faster to align many images than colmap) using kapture to colmap workflow. Having the same position of camera from the 3D model in blender as the gaussians in the viewer/renderer is necessary.

**Comment by yzslab** [comment]
> Hi, just for your information (as I struggled a lot before finding this issue), this default behavior should be more visible (in the readme or when you run the render).
> 
> The `--no-auto-reorient` isn't recognized as an argument on my side, I had to modify default value of `~nerfstudio/nerfstudio/scripts/gaussian_splatting/gaussian_splatting_config.py` line 38 to ` auto_reorient: bool = False`
> 
> I don't think this should be the default behavior, as for example it's possible to reuse an alignment from reality capture (faster to align many images than colmap) using kapture to colmap workflow. Having the same position of camera from the 3D model in blender as the gaussians in the viewer/renderer is necessary.

Hi, because I think the most users are using colmap, which almost always produce a wrong orientation, so use `auto_reorient=True` as the default will be more convient. I'll update the README later.
Thanks.
